version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: remotecom_etl
      POSTGRES_USER: remote
      POSTGRES_PASSWORD: remote.com

    ports:
      - "5432:5432"